# Generated by Django 5.1.6 on 2025-02-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='model_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
