# Generated by Django 5.1.6 on 2025-02-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_history_model_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='lime_image',
            field=models.FileField(null=True, upload_to='prediction_Lime_Image'),
        ),
    ]
